# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-18 05:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizeEmergencyMedicalTreatment',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('pref_medical_facility', models.CharField(max_length=70)),
                ('insurance_provider', models.CharField(max_length=70)),
                ('insurance_policy_num', models.CharField(max_length=20)),
                ('emerg_contact_name', models.CharField(max_length=75)),
                ('emerg_contact_phone', models.CharField(max_length=15)),
                ('emerg_contact_relation', models.CharField(max_length=50)),
                ('alt_emerg_procedure', models.CharField(max_length=500, null=True)),
                ('consents_emerg_med_treatment', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='BackgroundCheck',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('signature', models.CharField(max_length=75)),
                ('driver_license_num', models.CharField(max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='Caregiver',
            fields=[
                ('caregiver_ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=75)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ConfidentialityPolicy',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('agreement', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('diagnosis', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('diagnosis_type', models.CharField(choices=[('P', 'Primary'), ('S', 'Secondary')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('donation_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('donation_type', models.CharField(choices=[('H', 'Horse adoption'), ('P', 'Participant adoption'), ('M', 'Monetary donation')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('donor_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=75)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='EvalAttitude',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('walking_through_barn', models.CharField(blank=True, choices=[('A', 'Willing'), ('B', 'Willing, but needs encouragement'), ('C', 'Unwilling'), ('D', 'Well motivated'), ('E', 'Somewhat motivated'), ('F', 'Not motivated'), ('G', 'Smiles, appears happy'), ('H', 'Apprehensive about the whole thing')], max_length=1)),
                ('looking_at_horses', models.CharField(blank=True, choices=[('A', 'Willing'), ('B', 'Willing, but needs encouragement'), ('C', 'Unwilling'), ('D', 'Well motivated'), ('E', 'Somewhat motivated'), ('F', 'Not motivated'), ('G', 'Smiles, appears happy'), ('H', 'Apprehensive about the whole thing')], max_length=1)),
                ('petting_horses', models.CharField(blank=True, choices=[('A', 'Willing'), ('B', 'Willing, but needs encouragement'), ('C', 'Unwilling'), ('D', 'Well motivated'), ('E', 'Somewhat motivated'), ('F', 'Not motivated'), ('G', 'Smiles, appears happy'), ('H', 'Apprehensive about the whole thing')], max_length=1)),
                ('up_down_ramp', models.CharField(blank=True, choices=[('A', 'Willing'), ('B', 'Willing, but needs encouragement'), ('C', 'Unwilling'), ('D', 'Well motivated'), ('E', 'Somewhat motivated'), ('F', 'Not motivated'), ('G', 'Smiles, appears happy'), ('H', 'Apprehensive about the whole thing')], max_length=1)),
                ('mounting_before', models.CharField(blank=True, choices=[('A', 'Willing'), ('B', 'Willing, but needs encouragement'), ('C', 'Unwilling'), ('D', 'Well motivated'), ('E', 'Somewhat motivated'), ('F', 'Not motivated'), ('G', 'Smiles, appears happy'), ('H', 'Apprehensive about the whole thing')], max_length=1)),
                ('mounting_after', models.CharField(blank=True, choices=[('A', 'Willing'), ('B', 'Willing, but needs encouragement'), ('C', 'Unwilling'), ('D', 'Well motivated'), ('E', 'Somewhat motivated'), ('F', 'Not motivated'), ('G', 'Smiles, appears happy'), ('H', 'Apprehensive about the whole thing')], max_length=1)),
                ('riding_before', models.CharField(blank=True, choices=[('A', 'Willing'), ('B', 'Willing, but needs encouragement'), ('C', 'Unwilling'), ('D', 'Well motivated'), ('E', 'Somewhat motivated'), ('F', 'Not motivated'), ('G', 'Smiles, appears happy'), ('H', 'Apprehensive about the whole thing')], max_length=1)),
                ('riding_during', models.CharField(blank=True, choices=[('A', 'Willing'), ('B', 'Willing, but needs encouragement'), ('C', 'Unwilling'), ('D', 'Well motivated'), ('E', 'Somewhat motivated'), ('F', 'Not motivated'), ('G', 'Smiles, appears happy'), ('H', 'Apprehensive about the whole thing')], max_length=1)),
                ('riding_after', models.CharField(blank=True, choices=[('A', 'Willing'), ('B', 'Willing, but needs encouragement'), ('C', 'Unwilling'), ('D', 'Well motivated'), ('E', 'Somewhat motivated'), ('F', 'Not motivated'), ('G', 'Smiles, appears happy'), ('H', 'Apprehensive about the whole thing')], max_length=1)),
                ('understands_directions', models.CharField(blank=True, choices=[('A', 'Willing'), ('B', 'Willing, but needs encouragement'), ('C', 'Unwilling'), ('D', 'Well motivated'), ('E', 'Somewhat motivated'), ('F', 'Not motivated'), ('G', 'Smiles, appears happy'), ('H', 'Apprehensive about the whole thing')], max_length=1)),
                ('participates_exercises', models.CharField(blank=True, choices=[('A', 'Willing'), ('B', 'Willing, but needs encouragement'), ('C', 'Unwilling'), ('D', 'Well motivated'), ('E', 'Somewhat motivated'), ('F', 'Not motivated'), ('G', 'Smiles, appears happy'), ('H', 'Apprehensive about the whole thing')], max_length=1)),
                ('participates_games', models.CharField(blank=True, choices=[('A', 'Willing'), ('B', 'Willing, but needs encouragement'), ('C', 'Unwilling'), ('D', 'Well motivated'), ('E', 'Somewhat motivated'), ('F', 'Not motivated'), ('G', 'Smiles, appears happy'), ('H', 'Apprehensive about the whole thing')], max_length=1)),
                ('general_attitude', models.CharField(blank=True, choices=[('A', 'Willing'), ('B', 'Willing, but needs encouragement'), ('C', 'Unwilling'), ('D', 'Well motivated'), ('E', 'Somewhat motivated'), ('F', 'Not motivated'), ('G', 'Smiles, appears happy'), ('H', 'Apprehensive about the whole thing')], max_length=1)),
                ('comprehension', models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('P', 'Partially completes')], max_length=1)),
                ('confidence', models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('P', 'Partially completes')], max_length=1)),
                ('attention', models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('P', 'Partially completes')], max_length=1)),
                ('relaxation', models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('P', 'Partially completes')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='EvalHorsemanship',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('rules_and_reasons', models.NullBooleanField()),
                ('parts_of_horse', models.NullBooleanField()),
                ('parts_of_saddle', models.NullBooleanField()),
                ('parts_of_bridle', models.NullBooleanField()),
                ('approach_tied_horse', models.NullBooleanField()),
                ('methods_of_tying', models.NullBooleanField()),
                ('halter', models.NullBooleanField()),
                ('lead', models.NullBooleanField()),
                ('groom', models.NullBooleanField()),
                ('can_saddle_horse', models.NullBooleanField()),
                ('can_bridle_horse', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Grouping',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('horse_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=75)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='MediaRelease',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('consent', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('signature', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='ObservationEvaluation',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('class_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cbar_db.Grouping')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('participant_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=75)),
                ('birth_date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('weight', models.DecimalField(decimal_places=1, max_digits=4)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('guardian_name', models.CharField(max_length=75)),
                ('height', models.DecimalField(decimal_places=1, max_digits=4)),
                ('minor_status', models.CharField(choices=[('M', 'Minor'), ('G', 'Adult with guardian'), ('A', 'Independent adult')], max_length=1)),
                ('address_street', models.CharField(max_length=150)),
                ('address_city', models.CharField(max_length=50)),
                ('address_zip', models.CharField(max_length=6)),
                ('phone_home', models.CharField(max_length=15)),
                ('phone_cell_work', models.CharField(max_length=15)),
                ('school_institution', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantType',
            fields=[
                ('participant_type', models.CharField(choices=[('P', 'Participant'), ('V', 'Volunteer'), ('S', 'Staff')], max_length=1, primary_key=True, serialize=False)),
                ('participant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbar_db.Participant')),
            ],
        ),
        migrations.CreateModel(
            name='PhysRelease',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('health_provider_name', models.CharField(max_length=75)),
                ('health_provider_title', models.CharField(max_length=50)),
                ('health_provider_address', models.CharField(max_length=255)),
                ('health_provider_phone', models.CharField(max_length=15)),
                ('health_provider_signature', models.CharField(max_length=75)),
                ('health_provider_license_num', models.CharField(max_length=10)),
                ('participant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbar_db.Participant')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_ID', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('tack', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='SessionGoals',
            fields=[
                ('session_goals_id', models.AutoField(primary_key=True, serialize=False)),
                ('goal_type', models.CharField(choices=[('S', 'Short term goal'), ('L', 'Long term goal')], max_length=1)),
                ('goal_description', models.CharField(max_length=500)),
                ('motiviation', models.CharField(max_length=250)),
                ('participant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbar_db.Participant')),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbar_db.Session')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='session',
            unique_together=set([('session_ID', 'date')]),
        ),
        migrations.AddField(
            model_name='observationevaluation',
            name='participant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbar_db.Participant'),
        ),
        migrations.AddField(
            model_name='mediarelease',
            name='participant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbar_db.Participant'),
        ),
        migrations.AddField(
            model_name='evalhorsemanship',
            name='participant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbar_db.Participant'),
        ),
        migrations.AddField(
            model_name='evalattitude',
            name='participant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbar_db.Participant'),
        ),
        migrations.AddField(
            model_name='donation',
            name='donor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbar_db.Donor'),
        ),
        migrations.AddField(
            model_name='donation',
            name='horse_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbar_db.Horse'),
        ),
        migrations.AddField(
            model_name='donation',
            name='participant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbar_db.Participant'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='participant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbar_db.Participant'),
        ),
        migrations.AddField(
            model_name='confidentialitypolicy',
            name='participant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbar_db.Participant'),
        ),
        migrations.AddField(
            model_name='caregiver',
            name='participant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbar_db.Participant'),
        ),
        migrations.AddField(
            model_name='backgroundcheck',
            name='participant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbar_db.Participant'),
        ),
        migrations.AddField(
            model_name='authorizeemergencymedicaltreatment',
            name='participant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbar_db.Participant'),
        ),
        migrations.AlterUniqueTogether(
            name='sessiongoals',
            unique_together=set([('participant_id', 'session_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='physrelease',
            unique_together=set([('participant_id', 'date')]),
        ),
        migrations.AlterUniqueTogether(
            name='participanttype',
            unique_together=set([('participant_id', 'participant_type')]),
        ),
        migrations.AlterUniqueTogether(
            name='observationevaluation',
            unique_together=set([('participant_id', 'date')]),
        ),
        migrations.AlterUniqueTogether(
            name='mediarelease',
            unique_together=set([('participant_id', 'date')]),
        ),
        migrations.AlterUniqueTogether(
            name='evalhorsemanship',
            unique_together=set([('participant_id', 'date')]),
        ),
        migrations.AlterUniqueTogether(
            name='evalattitude',
            unique_together=set([('participant_id', 'date')]),
        ),
        migrations.AlterUniqueTogether(
            name='diagnosis',
            unique_together=set([('participant_id', 'diagnosis')]),
        ),
        migrations.AlterUniqueTogether(
            name='confidentialitypolicy',
            unique_together=set([('participant_id', 'date')]),
        ),
        migrations.AlterUniqueTogether(
            name='backgroundcheck',
            unique_together=set([('participant_id', 'date')]),
        ),
        migrations.AlterUniqueTogether(
            name='authorizeemergencymedicaltreatment',
            unique_together=set([('participant_id', 'date')]),
        ),
    ]
