# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-18 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('participant_ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=75)),
                ('birth_date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('weight', models.DecimalField(decimal_places=1, max_digits=4)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('guardian_name', models.CharField(max_length=75)),
                ('height', models.DecimalField(decimal_places=1, max_digits=4)),
                ('minor_status', models.CharField(choices=[('M', 'Minor'), ('G', 'Adult with guardian'), ('A', 'Independent adult')], max_length=1)),
                ('address_street', models.CharField(max_length=150)),
                ('address_city', models.CharField(max_length=50)),
                ('address_zip', models.CharField(max_length=6)),
                ('phone_home', models.CharField(max_length=15)),
                ('phone_cell_work', models.CharField(max_length=15)),
                ('school_institution', models.CharField(blank=True, max_length=150)),
            ],
        ),
    ]
