# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-18 02:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caregiver',
            fields=[
                ('caregiver_ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=75)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('participant_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=75)),
                ('birth_date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('weight', models.DecimalField(decimal_places=1, max_digits=4)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('guardian_name', models.CharField(max_length=75)),
                ('height', models.DecimalField(decimal_places=1, max_digits=4)),
                ('minor_status', models.CharField(choices=[('M', 'Minor'), ('G', 'Adult with guardian'), ('A', 'Independent adult')], max_length=1)),
                ('address_street', models.CharField(max_length=150)),
                ('address_city', models.CharField(max_length=50)),
                ('address_zip', models.CharField(max_length=6)),
                ('phone_home', models.CharField(max_length=15)),
                ('phone_cell_work', models.CharField(max_length=15)),
                ('school_institution', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_ID', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('tack', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='SessionGoals',
            fields=[
                ('session_goals_id', models.AutoField(primary_key=True, serialize=False)),
                ('goal_type', models.CharField(choices=[('S', 'Short term goal'), ('L', 'Long term goal')], max_length=1)),
                ('goal_description', models.CharField(max_length=500)),
                ('motiviation', models.CharField(max_length=250)),
                ('participant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbar_db.Participant')),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbar_db.Session')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='session',
            unique_together=set([('session_ID', 'date')]),
        ),
        migrations.AddField(
            model_name='caregiver',
            name='participant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbar_db.Participant'),
        ),
    ]
