# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-18 00:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cbar_db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caregiver',
            fields=[
                ('caregiver_ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=75)),
                ('phone', models.CharField(max_length=15)),
                ('participant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbar_db.Participant')),
            ],
        ),
    ]
