# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-25 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbar_db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizeemergencymedicaltreatment',
            name='signature',
            field=models.CharField(default='', max_length=75),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='authorizeemergencymedicaltreatment',
            name='consents_emerg_med_treatment',
            field=models.CharField(choices=[('Y', 'consent'), ('N', 'do not consent')], max_length=1),
        ),
        migrations.AlterField(
            model_name='mediarelease',
            name='consent',
            field=models.CharField(choices=[('Y', 'consent'), ('N', 'do not consent')], max_length=1),
        ),
    ]
