# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-18 02:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbar_db', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sessiongoals',
            unique_together=set([('participant_id', 'session_id')]),
        ),
    ]
