# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-16 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbar_db', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='duration_taken',
        ),
        migrations.AddField(
            model_name='medication',
            name='reason_taken',
            field=models.CharField(max_length=50),
        ),
    ]
