# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-18 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbar_db', '0002_caregiver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_ID', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('tack', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='session',
            unique_together=set([('session_ID', 'date')]),
        ),
    ]
