# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-30 21:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbar_db', '0002_added_signature_field_to_AuthorizeEmergencyMedicalTreatment'),
        ('cbar_db', '0002_change_boolean_fields_in_medicalinfo_to_choice_fields'),
    ]

    operations = [
    ]
