# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-16 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbar_db', '0002_change_duration_taken_field_to_reason_taken_in_medication_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confidentialitypolicy',
            name='agreement',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
    ]
