# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-16 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbar_db', '0003_change_agreement_field_in_confidentialitypolicy_model_to_booleanfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='frequency',
            field=models.CharField(max_length=50),
        ),
    ]
