# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-30 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbar_db', '0003_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalinfo',
            name='currently_taking_any_medication',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1),
            preserve_default=False,
        ),
    ]
