# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-30 22:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cbar_db', '0004_added_currently_taking_any_medications_attribute_to_medicalinfo_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='medical_info_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cbar_db.MedicalInfo'),
        ),
        # migrations.RemoveField(
        #     model_name='medication',
        #     name='participant_id',
        # ),
        migrations.AlterUniqueTogether(
            name='medication',
            unique_together=set([('medical_info_id', 'medication_name')]),
        ),
        migrations.RemoveField(
        model_name='medicalinfo',
        name='medication_name',
        ),
    ]
