# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-17 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbar_db', '0005_add_address_state_field_to_participant_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='phone_cell',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='phone_home',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='phone_work',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
