# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-31 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbar_db', '0006_removed_unneeded_fk_from_medicalinfo_table_and_changed_pk_of_medication_table_2_of_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalinfo',
            name='limiting_surgeries_last_six_monthes_description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
