# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-21 14:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbar_db', '0006_set_null_true_on_participant_model_phone_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessiongoals',
            old_name='motiviation',
            new_name='motivation',
        ),
    ]
