# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-20 13:41
from __future__ import unicode_literals

from django.db import migrations
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('cbar_db', '0006_set_null_true_on_participant_model_phone_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorizeemergencymedicaltreatment',
            name='emerg_contact_phone',
            field=localflavor.us.models.PhoneNumberField(max_length=20),
        ),
        migrations.AlterField(
            model_name='caregiver',
            name='phone',
            field=localflavor.us.models.PhoneNumberField(max_length=20),
        ),
        migrations.AlterField(
            model_name='medicalinfo',
            name='primary_physician_phone',
            field=localflavor.us.models.PhoneNumberField(max_length=20),
        ),
        migrations.AlterField(
            model_name='participant',
            name='phone_cell',
            field=localflavor.us.models.PhoneNumberField(max_length=20),
        ),
        migrations.AlterField(
            model_name='participant',
            name='phone_home',
            field=localflavor.us.models.PhoneNumberField(max_length=20),
        ),
        migrations.AlterField(
            model_name='participant',
            name='phone_work',
            field=localflavor.us.models.PhoneNumberField(max_length=20),
        ),
        migrations.AlterField(
            model_name='physrelease',
            name='health_provider_phone',
            field=localflavor.us.models.PhoneNumberField(max_length=20),
        ),
    ]
