# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-21 00:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cbar_db', '0006_set_null_true_on_participant_model_phone_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cbar_db.Donor'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='horse_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cbar_db.Horse'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='participant_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cbar_db.Participant'),
        ),
    ]
