# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-02 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbar_db', '0007_added_limiting_surgeries_last_six_monthes_description_to_medicalinfo_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalinfo',
            name='allergies_conditions_that_exclude',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], max_length=1),
        ),
    ]
