# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-21 17:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbar_db', '0008_change_address_zip_field_to_localflavor'),
        ('cbar_db', '0007_change_donation_fks_to_allow_null_values'),
    ]

    operations = [
    ]
