# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-01 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbar_db', '0009_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='seizureeval',
            name='type_of_seizure',
            field=models.CharField(choices=[('G', 'Grand'), ('P', 'Petite'), ('C', 'Controlled'), ('N', 'None')], max_length=1),
        ),
    ]
