# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-28 06:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbar_db', '0007_renamed_motiviation_field_in_sessiongoals_model_to_motivation'),
        ('cbar_db', '0009_merge'),
    ]

    operations = [
    ]
