# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-05 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbar_db', '0010_added_liabilityrelease_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='phone_cell_work',
        ),
        migrations.AddField(
            model_name='participant',
            name='phone_cell',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='phone_work',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
