# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-05 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbar_db', '0011_split_phone_cell_work_into_two_fields_in_participant_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seizureeval',
            old_name='during_seizure_other',
            new_name='during_seizure_other_description',
        ),
        migrations.AddField(
            model_name='seizureeval',
            name='seizure_frequency',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
