# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-01 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbar_db', '0011_remove_seizuretype_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evalridingexercises',
            name='basic_control',
            field=models.NullBooleanField(choices=[(True, 'Yes'), (False, 'No'), ('', 'Unknown')]),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='basic_seat_english',
            field=models.NullBooleanField(choices=[(True, 'Yes'), (False, 'No'), ('', 'Unknown')]),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='basic_seat_western',
            field=models.NullBooleanField(choices=[(True, 'Yes'), (False, 'No'), ('', 'Unknown')]),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='basic_trail_rules',
            field=models.NullBooleanField(choices=[(True, 'Yes'), (False, 'No'), ('', 'Unknown')]),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='circle_at_canter',
            field=models.NullBooleanField(choices=[(True, 'Yes'), (False, 'No'), ('', 'Unknown')]),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='circle_at_trot',
            field=models.NullBooleanField(choices=[(True, 'Yes'), (False, 'No'), ('', 'Unknown')]),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='circle_at_walk',
            field=models.NullBooleanField(choices=[(True, 'Yes'), (False, 'No'), ('', 'Unknown')]),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='circle_canter_no_stirrups',
            field=models.NullBooleanField(choices=[(True, 'Yes'), (False, 'No'), ('', 'Unknown')]),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='circle_trot_no_stirrups',
            field=models.NullBooleanField(choices=[(True, 'Yes'), (False, 'No'), ('', 'Unknown')]),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='dismount',
            field=models.NullBooleanField(choices=[(True, 'Yes'), (False, 'No'), ('', 'Unknown')]),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='emergency_dismount',
            field=models.NullBooleanField(choices=[(True, 'Yes'), (False, 'No'), ('', 'Unknown')]),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='four_natural_aids',
            field=models.NullBooleanField(choices=[(True, 'Yes'), (False, 'No'), ('', 'Unknown')]),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='hand_pos_english',
            field=models.NullBooleanField(choices=[(True, 'Yes'), (False, 'No'), ('', 'Unknown')]),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='hand_post_western',
            field=models.NullBooleanField(choices=[(True, 'Yes'), (False, 'No'), ('', 'Unknown')]),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='mount',
            field=models.NullBooleanField(choices=[(True, 'Yes'), (False, 'No'), ('', 'Unknown')]),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='never_ridden',
            field=models.NullBooleanField(choices=[(True, 'Yes'), (False, 'No'), ('', 'Unknown')]),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='reverse_at_trot',
            field=models.NullBooleanField(choices=[(True, 'Yes'), (False, 'No'), ('', 'Unknown')]),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='reverse_at_walk',
            field=models.NullBooleanField(choices=[(True, 'Yes'), (False, 'No'), ('', 'Unknown')]),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='seat_at_canter',
            field=models.NullBooleanField(choices=[(True, 'Yes'), (False, 'No'), ('', 'Unknown')]),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='seat_at_trot',
            field=models.NullBooleanField(choices=[(True, 'Yes'), (False, 'No'), ('', 'Unknown')]),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='seat_at_walk',
            field=models.NullBooleanField(choices=[(True, 'Yes'), (False, 'No'), ('', 'Unknown')]),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='two_point_canter',
            field=models.NullBooleanField(choices=[(True, 'Yes'), (False, 'No'), ('', 'Unknown')]),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='two_point_trot',
            field=models.NullBooleanField(choices=[(True, 'Yes'), (False, 'No'), ('', 'Unknown')]),
        ),
    ]
