# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-05 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbar_db', '0012_renamed_during_seizure_other_to_during_seizure_other_description_added_seizure_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='seizureeval',
            name='during_seizure_other',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
