# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-02 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbar_db', '0012_change_fields_in_evalridingexercises_to_radio_buttons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evalphysical',
            name='arm_circle_back_halt',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalphysical',
            name='arm_circle_back_walk',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalphysical',
            name='arm_circle_fwd_halt',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalphysical',
            name='arm_circle_fwd_walk',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalphysical',
            name='arms_head_halt',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalphysical',
            name='arms_head_walk',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalphysical',
            name='arms_side_halt',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalphysical',
            name='arms_side_walk',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalphysical',
            name='bend_foot_down_halt',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalphysical',
            name='bend_foot_down_walk',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalphysical',
            name='bend_foot_up_halt',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalphysical',
            name='bend_foot_up_walk',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalphysical',
            name='foot_circles_halt',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalphysical',
            name='foot_circles_walk',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalphysical',
            name='hand_circle_halt',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalphysical',
            name='hand_circle_walk',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalphysical',
            name='lie_back_halt',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalphysical',
            name='lie_back_walk',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalphysical',
            name='stand_in_stirrups_halt',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalphysical',
            name='stand_in_stirrups_walk',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalphysical',
            name='swing_legs_back_halt',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalphysical',
            name='swing_legs_back_walk',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalphysical',
            name='swing_legs_halt',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalphysical',
            name='swing_legs_walk',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalphysical',
            name='touch_both_toes_halt',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalphysical',
            name='touch_both_toes_walk',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalphysical',
            name='touch_ears_halt',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalphysical',
            name='touch_ears_walk',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalphysical',
            name='touch_left_tow_w_right_hand_halt',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalphysical',
            name='touch_left_tow_w_right_hand_walk',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalphysical',
            name='touch_right_tow_w_left_hand_halt',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalphysical',
            name='touch_right_tow_w_left_hand_walk',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalphysical',
            name='touch_tail_walk',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalphysical',
            name='touch_talk_halt',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalphysical',
            name='twist_halt',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalphysical',
            name='twist_walk',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='basic_control',
            field=models.NullBooleanField(choices=[(1, 'Yes'), (0, 'No'), (2, 'Unknown')]),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='basic_seat_english',
            field=models.NullBooleanField(choices=[(1, 'Yes'), (0, 'No'), (2, 'Unknown')]),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='basic_seat_western',
            field=models.NullBooleanField(choices=[(1, 'Yes'), (0, 'No'), (2, 'Unknown')]),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='basic_trail_rules',
            field=models.NullBooleanField(choices=[(1, 'Yes'), (0, 'No'), (2, 'Unknown')]),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='can_control_horse_canter',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='can_control_horse_post_trot',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='can_control_horse_sit_trot',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='can_control_horse_walk',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='can_halt_canter',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='can_halt_post_trot',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='can_halt_sit_trot',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='can_halt_walk',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='can_post_canter',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='can_post_post_trot',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='can_post_sit_trot',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='can_post_walk',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='can_steer_over_cavalletti_canter',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='can_steer_over_cavalletti_post_trot',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='can_steer_over_cavalletti_sit_trot',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='can_steer_over_cavalletti_walk',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='circle_at_canter',
            field=models.NullBooleanField(choices=[(1, 'Yes'), (0, 'No'), (2, 'Unknown')]),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='circle_at_trot',
            field=models.NullBooleanField(choices=[(1, 'Yes'), (0, 'No'), (2, 'Unknown')]),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='circle_at_walk',
            field=models.NullBooleanField(choices=[(1, 'Yes'), (0, 'No'), (2, 'Unknown')]),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='circle_canter_no_stirrups',
            field=models.NullBooleanField(choices=[(1, 'Yes'), (0, 'No'), (2, 'Unknown')]),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='circle_trot_no_stirrups',
            field=models.NullBooleanField(choices=[(1, 'Yes'), (0, 'No'), (2, 'Unknown')]),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='dismount',
            field=models.NullBooleanField(choices=[(1, 'Yes'), (0, 'No'), (2, 'Unknown')]),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='drop_pickup_stirrups_canter',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='drop_pickup_stirrups_post_trot',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='drop_pickup_stirrups_sit_trot',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='drop_pickup_stirrups_walk',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='emergency_dismount',
            field=models.NullBooleanField(choices=[(1, 'Yes'), (0, 'No'), (2, 'Unknown')]),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='four_natural_aids',
            field=models.NullBooleanField(choices=[(1, 'Yes'), (0, 'No'), (2, 'Unknown')]),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='hand_pos_english',
            field=models.NullBooleanField(choices=[(1, 'Yes'), (0, 'No'), (2, 'Unknown')]),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='hand_post_western',
            field=models.NullBooleanField(choices=[(1, 'Yes'), (0, 'No'), (2, 'Unknown')]),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='holds_handhold_canter',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='holds_handhold_post_trot',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='holds_handhold_sit_trot',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='holds_handhold_walk',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='holds_reins_canter',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='holds_reins_post_trot',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='holds_reins_sit_trot',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='holds_reins_walk',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='jump_crossbar_canter',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='jump_crossbar_post_trot',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='jump_crossbar_sit_trot',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='jump_crossbar_walk',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='maintain_half_seat_canter',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='maintain_half_seat_post_trot',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='maintain_half_seat_sit_trot',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='maintain_half_seat_walk',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='mount',
            field=models.NullBooleanField(choices=[(1, 'Yes'), (0, 'No'), (2, 'Unknown')]),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='never_ridden',
            field=models.NullBooleanField(choices=[(1, 'Yes'), (0, 'No'), (2, 'Unknown')]),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='proper_diagonal_canter',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='proper_diagonal_post_trot',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='proper_diagonal_sit_trot',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='proper_diagonal_walk',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='proper_lead_canter_knows',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='proper_lead_canter_sees',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='reverse_at_trot',
            field=models.NullBooleanField(choices=[(1, 'Yes'), (0, 'No'), (2, 'Unknown')]),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='reverse_at_walk',
            field=models.NullBooleanField(choices=[(1, 'Yes'), (0, 'No'), (2, 'Unknown')]),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='rides_no_stirrups_canter',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='rides_no_stirrups_post_trot',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='rides_no_stirrups_sit_trot',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='rides_no_stirrups_walk',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='seat_at_canter',
            field=models.NullBooleanField(choices=[(1, 'Yes'), (0, 'No'), (2, 'Unknown')]),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='seat_at_trot',
            field=models.NullBooleanField(choices=[(1, 'Yes'), (0, 'No'), (2, 'Unknown')]),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='seat_at_walk',
            field=models.NullBooleanField(choices=[(1, 'Yes'), (0, 'No'), (2, 'Unknown')]),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='shorten_lengthen_reins_canter',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='shorten_lengthen_reins_post_trot',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='shorten_lengthen_reins_sit_trot',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='shorten_lengthen_reins_walk',
            field=models.CharField(blank=True, choices=[('U', 'Unsatisfactory'), ('P', 'Poor'), ('F', 'Fair'), ('G', 'Good'), ('E', 'Excellent'), ('N', 'Rider not able to perform due to disability'), ('A', 'Attempts'), ('C', 'Partially completes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='two_point_canter',
            field=models.NullBooleanField(choices=[(1, 'Yes'), (0, 'No'), (2, 'Unknown')]),
        ),
        migrations.AlterField(
            model_name='evalridingexercises',
            name='two_point_trot',
            field=models.NullBooleanField(choices=[(1, 'Yes'), (0, 'No'), (2, 'Unknown')]),
        ),
    ]
