# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-02 05:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbar_db', '0013_change_partially_completes_choice_from_p_to_c'),
        ('cbar_db', '0010_merge'),
    ]

    operations = [
    ]
