# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-05 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbar_db', '0013_added_during_seizure_other_description_field_to_seizureeval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seizureeval',
            name='actions_to_take',
        ),
        migrations.AddField(
            model_name='seizureeval',
            name='action_to_take_allow_time',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seizureeval',
            name='action_to_take_allow_time_how_long',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seizureeval',
            name='action_to_take_dismount',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seizureeval',
            name='action_to_take_do_nothing',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seizureeval',
            name='action_to_take_report_immediately',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seizureeval',
            name='action_to_take_send_note',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
