# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-05 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbar_db', '0014_changed_actions_to_take_to_multiple_booleanfields_in_seizureeval'),
    ]

    operations = [
        migrations.AddField(
            model_name='seizureeval',
            name='signature',
            field=models.CharField(default='', max_length=75),
            preserve_default=False,
        ),
    ]
