# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-02 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbar_db', '0014_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='purpose',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
