# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-02 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbar_db', '0016_add_date_field_to_donation_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seizureeval',
            name='action_to_take_allow_time_how_long',
            field=models.DecimalField(decimal_places=0, max_digits=2, null=True),
        ),
    ]
