# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-06 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbar_db', '0016_changed_duration_of_last_seizure_field_in_seizureevaluation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seizureeval',
            name='during_seizure_stare_length',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
