# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-02 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbar_db', '0017_set_null_true_on_action_to_take_allow_how_long_field_seizureeval'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalinfo',
            name='pregnant',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
    ]
