# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-06 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cbar_db', '0017_changed_during_seizure_stare_length_in_seizureevaluation_to_charfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seizureeval',
            name='type_of_seizure',
        ),
        migrations.AddField(
            model_name='seizuretype',
            name='seizure_eval',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbar_db.SeizureEval')
        ),
        migrations.AlterUniqueTogether(
            name='seizuretype',
            unique_together=set([('seizure_eval', 'name')]),
        ),
    ]
