# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-06 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbar_db', '0018_added_seizureeval_fk_to_seizuretype_model_and_removed_seizuretype_fk_from_seizureeval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seizureeval',
            name='action_to_take_allow_time',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='seizureeval',
            name='action_to_take_dismount',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='seizureeval',
            name='action_to_take_do_nothing',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='seizureeval',
            name='action_to_take_report_immediately',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='seizureeval',
            name='action_to_take_send_note',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='seizureeval',
            name='can_communicate_when_will_occur',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='seizureeval',
            name='during_seizure_aimless',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='seizureeval',
            name='during_seizure_bladder_bowel',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='seizureeval',
            name='during_seizure_confused_etc',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='seizureeval',
            name='during_seizure_cry_etc',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='seizureeval',
            name='during_seizure_other',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='seizureeval',
            name='during_seizure_stare',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='seizureeval',
            name='during_seizure_walks',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='seizureeval',
            name='knows_when_will_occur',
            field=models.NullBooleanField(),
        ),
    ]
