# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-04 20:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbar_db', '0018_added_pregnant_field_to_medicalinfo_model'),
        ('cbar_db', '0017_added_comment_fields_in_rider_eval_checklist'),
    ]

    operations = [
    ]
