# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-04 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbar_db', '0019_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalinfo',
            name='allergies_conditions_that_exclude',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1),
        ),
    ]
