# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-05 01:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbar_db', '0019_merge'),
        ('cbar_db', '0012_split_fields_in_ridingeval_model_into_willing_motivated_appearence_fields'),
    ]

    operations = [
    ]
