# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-09 22:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cbar_db', '0019_changed_booleanfields_in_seizureeval_model_to_nullbooleanfields'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='date',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='medication',
            name='participant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbar_db.Participant'),
        ),
        # migrations.RemoveField(
        #     model_name='medication',
        #     name='medical_info_id',
        # ),
        migrations.AlterUniqueTogether(
            name='medication',
            unique_together=set([('participant_id', 'date', 'medication_name')]),
        ),
    ]
