# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-05 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbar_db', '0020_change_yes_no_bool_choices_to_yes_no_choices_part_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confidentialitypolicy',
            name='agreement',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1),
        ),
        migrations.AlterField(
            model_name='medicalinfo',
            name='currently_taking_any_medication',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1),
        ),
        migrations.AlterField(
            model_name='medicalinfo',
            name='doctor_concered_re_horse_activites',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1),
        ),
        migrations.AlterField(
            model_name='medicalinfo',
            name='heat_exhaustion_stroke',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1),
        ),
        migrations.AlterField(
            model_name='medicalinfo',
            name='limiting_surgeries_last_six_monthes',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1),
        ),
        migrations.AlterField(
            model_name='medicalinfo',
            name='physical_or_mental_issues_affecting_riding',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1),
        ),
        migrations.AlterField(
            model_name='medicalinfo',
            name='pregnant',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1),
        ),
        migrations.AlterField(
            model_name='medicalinfo',
            name='present_restrictions_for_horse_activity',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1),
        ),
        migrations.AlterField(
            model_name='medicalinfo',
            name='restriction_for_horse_activity_last_five_years',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1),
        ),
        migrations.AlterField(
            model_name='medicalinfo',
            name='seizures_last_six_monthes',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1),
        ),
        migrations.AlterField(
            model_name='medicalinfo',
            name='tetanus_shot_last_ten_years',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1),
        ),
    ]
