# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-09 22:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbar_db', '0020_changed_medication_model_fk_to_participant_id_date_medication_name_1_of_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='medical_info_id',
        ),
    ]
