# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-05 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbar_db', '0021_change_yes_no_bool_choices_to_yes_no_choices_part_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='horse',
            name='horse_leader',
            field=models.CharField(max_length=75, null=True),
        ),
    ]
