# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-06 16:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbar_db', '0021_change_yes_no_bool_choices_to_yes_no_choices_part_2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adaptationsneeded',
            old_name='gait_standing_down',
            new_name='gait_sitting_down',
        ),
    ]
