# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-05 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cbar_db', '0022_horse_horse_leader'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionPlanInd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('horse_leader', models.CharField(max_length=75, null=True)),
                ('participant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbar_db.Participant')),
            ],
        ),
        migrations.RemoveField(
            model_name='horse',
            name='horse_leader',
        ),
        migrations.AlterUniqueTogether(
            name='sessionplanind',
            unique_together=set([('participant_id', 'date')]),
        ),
    ]
