# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-08 16:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cbar_db', '0023_auto_20160505_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='incidents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('details', models.CharField(max_length=500)),
                ('participant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbar_db.Participant')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('details', models.CharField(max_length=500)),
                ('participant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbar_db.Participant')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='phonelog',
            unique_together=set([('participant_id', 'date')]),
        ),
        migrations.AlterUniqueTogether(
            name='incidents',
            unique_together=set([('participant_id', 'date')]),
        ),
    ]
