# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-07 16:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbar_db', '0023_auto_20160505_1011'),
        ('cbar_db', '0021_changed_ONE_TWO_THREE_CHOICES_-_label_to_na'),
    ]

    operations = [
    ]
