# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-07 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbar_db', '0024_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='tack',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
