# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-09 04:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbar_db', '0025_added_code_to_make_tack_not_required'),
        ('cbar_db', '0025_auto_20160508_1604'),
    ]

    operations = [
    ]
