# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-08 03:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbar_db', '0025_added_code_to_make_tack_not_required'),
        ('cbar_db', '0023_changed_gait_fields_to_ASSISTANCE_CHOICES_NA_ChoiceFields_in_adaptationsneeded_model'),
    ]

    operations = [
    ]
