# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-08 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbar_db', '0026_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adaptationsneeded',
            name='posture_mounted',
            field=models.CharField(choices=[('I', 'Independent'), ('M', 'Minimal asst.'), ('F', 'Full asst.'), ('N', 'n/a')], default='N', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='adaptationsneeded',
            name='posture_sitting',
            field=models.CharField(choices=[('I', 'Independent'), ('M', 'Minimal asst.'), ('F', 'Full asst.'), ('N', 'n/a')], default='N', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='adaptationsneeded',
            name='posture_standing',
            field=models.CharField(choices=[('I', 'Independent'), ('M', 'Minimal asst.'), ('F', 'Full asst.'), ('N', 'n/a')], default='N', max_length=1, null=True),
        ),
    ]
