# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-09 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbar_db', '0026_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonelog',
            name='time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='phonelog',
            name='details',
            field=models.CharField(max_length=2500),
        ),
        migrations.AlterUniqueTogether(
            name='phonelog',
            unique_together=set([('participant_id', 'date', 'time')]),
        ),
    ]
