# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-09 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbar_db', '0027_add_time_field_increase_description_max_length_and_set_pk_to_date+time+participant_id_in_phonelog_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidents',
            name='time',
            field=models.TimeField()
        ),
        migrations.AlterField(
            model_name='incidents',
            name='details',
            field=models.CharField(max_length=2500),
        ),
        migrations.AlterUniqueTogether(
            name='incidents',
            unique_together=set([('participant_id', 'date', 'time')]),
        ),
    ]
