# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-08 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbar_db', '0027_modified_posture_fields_in_adaptationsneeded_model_to_use_ASSISTANCE_CHOICES_NA'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='handedness',
            field=models.CharField(choices=[('L', 'Left'), ('R', 'Right'), ('A', 'Ambidextrous'), ('N', 'No meaningful hand use')], max_length=1, null=True),
        ),
    ]
