# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-08 07:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cbar_db', '0028_added_handedness_field_to_participant_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntakeAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('staff_reviewed_medical_info', models.BooleanField()),
                ('staff_reviewed_medical_info_date', models.DateField()),
                ('precautions', models.CharField(max_length=500)),
                ('impulsive', models.BooleanField()),
                ('eye_contact', models.BooleanField()),
                ('attention_span', models.CharField(choices=[('P', 'Poor'), ('F', 'Fair'), ('G', 'Good')], max_length=1)),
                ('interacts_with_others', models.BooleanField()),
                ('communication_verbal', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('I', 'Impaired')], max_length=1, null=True)),
                ('communication_verbal_comments', models.CharField(max_length=100)),
                ('language_skills_signs', models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('S', 'Some')], max_length=1, null=True)),
                ('language_skills_comments', models.CharField(max_length=100, null=True)),
                ('visual_impaired', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True)),
                ('visual_comments', models.CharField(max_length=100, null=True)),
                ('hearing_impaired', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True)),
                ('hearing_comments', models.CharField(max_length=100, null=True)),
                ('tactile', models.CharField(choices=[('N', 'No tactile issues'), ('T', "Don't touch me!"), ('L', 'Light touch'), ('P', 'Deep pressure')], max_length=1, null=True)),
                ('tactile_comments', models.CharField(max_length=100, null=True)),
                ('motor_skills_gross_left', models.CharField(choices=[('I', 'Independent'), ('M', 'Minimal asst.'), ('F', 'Full asst.'), ('N', 'n/a')], default='N', max_length=1, null=True)),
                ('motor_skills_gross_right', models.CharField(choices=[('I', 'Independent'), ('M', 'Minimal asst.'), ('F', 'Full asst.'), ('N', 'n/a')], default='N', max_length=1, null=True)),
                ('motor_skills_fine_left', models.CharField(choices=[('I', 'Independent'), ('M', 'Minimal asst.'), ('F', 'Full asst.'), ('N', 'n/a')], default='N', max_length=1, null=True)),
                ('motor_skills_fine_right', models.CharField(choices=[('I', 'Independent'), ('M', 'Minimal asst.'), ('F', 'Full asst.'), ('N', 'n/a')], default='N', max_length=1, null=True)),
                ('motor_skills_comments', models.CharField(max_length=100, null=True)),
                ('posture_forward_halt', models.NullBooleanField()),
                ('posture_forward_walk', models.NullBooleanField()),
                ('posture_back_halt', models.NullBooleanField()),
                ('posture_back_walk', models.NullBooleanField()),
                ('posture_center_halt', models.NullBooleanField()),
                ('posture_center_walk', models.NullBooleanField()),
                ('posture_chairseat_halt', models.NullBooleanField()),
                ('posture_chairseat_walk', models.NullBooleanField()),
                ('posture_aligned_halt', models.NullBooleanField()),
                ('posture_aligned_walk', models.NullBooleanField()),
                ('rein_use_hold_halt', models.CharField(choices=[('I', 'Independent'), ('M', 'Minimal asst.'), ('F', 'Full asst.'), ('N', 'n/a')], default='N', max_length=1, null=True)),
                ('rein_use_steer_left_right_halt', models.CharField(choices=[('I', 'Independent'), ('M', 'Minimal asst.'), ('F', 'Full asst.'), ('N', 'n/a')], default='N', max_length=1, null=True)),
                ('rein_use_hold_walk', models.CharField(choices=[('I', 'Independent'), ('M', 'Minimal asst.'), ('F', 'Full asst.'), ('N', 'n/a')], default='N', max_length=1, null=True)),
                ('rein_use_steer_left_right_walk', models.CharField(choices=[('I', 'Independent'), ('M', 'Minimal asst.'), ('F', 'Full asst.'), ('N', 'n/a')], default='N', max_length=1, null=True)),
                ('mounted_comments', models.CharField(max_length=100)),
                ('risk_benefit_comments', models.CharField(max_length=500)),
                ('participant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbar_db.Participant')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='intakeassessment',
            unique_together=set([('participant_id', 'date')]),
        ),
    ]
