# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-08 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbar_db', '0029_added_intakeassessment_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intakeassessment',
            name='eye_contact',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1),
        ),
        migrations.AlterField(
            model_name='intakeassessment',
            name='impulsive',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1),
        ),
        migrations.AlterField(
            model_name='intakeassessment',
            name='interacts_with_others',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1),
        ),
        migrations.AlterField(
            model_name='intakeassessment',
            name='staff_reviewed_medical_info',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1),
        ),
    ]
