# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-08 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbar_db', '0030_changed_booleanfields_in_intakeassessment_model_to_YES_NO_CHOICES_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='intakeassessment',
            name='goals_expectations',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
