# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-12 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbar_db', '0030_auto_20160511_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': ('admin', 'Admin'),
            },
        ),
        migrations.AlterModelOptions(
            name='authorizeduser',
            options={},
        ),
    ]
