# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-11 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbar_db', '0031_add_goals_expectations_field_to_intakeassessment_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adaptationsneeded',
            name='ambulatory_status',
            field=models.CharField(choices=[('I', 'Walks independently'), ('C', 'Independent with cane/bronco/walker'), ('N', 'Wheelchair with minimal or no assistance'), ('A', 'Wheelchair with full assistance'), ('O', 'Other')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='adaptationsneeded',
            name='dismount_assistance_required',
            field=models.CharField(choices=[('I', 'Independent'), ('M', 'Minimal assistance'), ('F', 'Full assistance')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='adaptationsneeded',
            name='dismount_type',
            field=models.CharField(choices=[('A', 'Over croup'), ('B', 'Over croup with left foot in stirrup'), ('C', 'Over crest')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='adaptationsneeded',
            name='mount_assistance_required',
            field=models.CharField(choices=[('I', 'Independent'), ('M', 'Minimal assistance'), ('F', 'Full assistance')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='adaptationsneeded',
            name='num_sidewalkers_trot_heel_hold',
            field=models.DecimalField(decimal_places=0, max_digits=1, null=True),
        ),
        migrations.AlterField(
            model_name='adaptationsneeded',
            name='num_sidewalkers_trot_other',
            field=models.DecimalField(decimal_places=0, max_digits=1, null=True),
        ),
        migrations.AlterField(
            model_name='adaptationsneeded',
            name='num_sidewalkers_trot_over_thigh',
            field=models.DecimalField(decimal_places=0, max_digits=1, null=True),
        ),
        migrations.AlterField(
            model_name='adaptationsneeded',
            name='num_sidewalkers_trot_spotter',
            field=models.DecimalField(decimal_places=0, max_digits=1, null=True),
        ),
        migrations.AlterField(
            model_name='adaptationsneeded',
            name='num_sidewalkers_walk_heel_hold',
            field=models.DecimalField(decimal_places=0, max_digits=1, null=True),
        ),
        migrations.AlterField(
            model_name='adaptationsneeded',
            name='num_sidewalkers_walk_other',
            field=models.DecimalField(decimal_places=0, max_digits=1, null=True),
        ),
        migrations.AlterField(
            model_name='adaptationsneeded',
            name='num_sidewalkers_walk_over_thigh',
            field=models.DecimalField(decimal_places=0, max_digits=1, null=True),
        ),
        migrations.AlterField(
            model_name='adaptationsneeded',
            name='num_sidewalkers_walk_spotter',
            field=models.DecimalField(decimal_places=0, max_digits=1, null=True),
        ),
    ]
