# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-12 01:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbar_db', '0033_auto_20160511_2026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpermission',
            options={'permissions': (('test_admin', 'Test Admin'), ('test_user', 'Test User'))},
        ),
    ]
