# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-12 01:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbar_db', '0034_auto_20160511_2032'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPermission',
        ),
    ]
